[package]
authors = ["Dhruv kumar <darbaga10@gmail.com>"]
name = "tolk-sys"
description = "Raw ffi bindings to Tolk.dll"
repository = "https://github.com/darbaga/tolk-sys"
readme = "README.md"
categories = ["external-ffi-bindings"]
license = "MIT"
version = "0.1.0"

[dependencies]
libc = "0.2.20"
